# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bc9f20be2628ec85842d749285f37dbce0db3757817ac3d09883d5f5cad844af08d75377cdfc3e5a9fd0587bf6ff8f63391421aa7ffaf5a4b393c191b739f3f

test:
  secret_key_base: 0fd4b6f2672fb1a743b2dedcdaeedb2fb7949da06074d67f149b2054dcb31f74b51d100a2c01965d38d923747f1330a7ff47728508f5f92d959eb667a11fe3b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
